# Generated by Django 2.1.4 on 2018-12-30 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direct_purchase', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_company', models.CharField(max_length=255)),
                ('flight_number', models.CharField(max_length=50)),
                ('departure_city', models.CharField(max_length=255)),
                ('transfer_city', models.CharField(blank=True, max_length=255, null=True)),
                ('arrival_city', models.CharField(max_length=255)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('total_price', models.IntegerField()),
                ('total_tickets', models.IntegerField()),
                ('delay_state', models.BooleanField(default=False)),
                ('cancel_state', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay_time', models.TimeField(blank=True, null=True)),
                ('message', models.TextField()),
                ('cancel_state', models.BooleanField(default=False)),
                ('affected_flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Flight')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='book_flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Flight'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
