# Generated by Django 2.1.4 on 2018-12-30 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='cancel_state',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='delay_state',
        ),
    ]
